# SPDX-License-Identifier: MIT
#
# West manifest for building the nRF52833 ESB dongle firmware.

manifest:
  self:
    path: app

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v3.7.0
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - mcuboot
          - zephyr
          - net-tools
