# SPDX-License-Identifier: MIT
# Zephyr manifest for ESB dongle

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.2.0
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - kconfiglib
          - libmetal
          - mbedtls
          - tinycrypt
          - zcbor
          - zephyr
          - zlib
  self:
    path: .